pyapi:
  name: portal-pyapi
  replicaCount: 1
  image:
    repository: docker-registry.local-env:5000/app__pyapi
    tag: latest
    pullPolicy: Never
  ## gitlab
  # image:
  #   repository: 'registry.gitlab.com/artas90/k8s-portal/pyapi'
  #   tag: latest
  #   pullPolicy: Never
  #   imagePullSecrets: registry-credentials
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

ngui:
  name: portal-ngui
  replicaCount: 1
  image:
    repository: docker-registry.local-env:5000/app__ngui
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
